import os
import numpy as np
import matplotlib.pyplot as plt
import re
import pathlib
from collections import defaultdict

def plot_residuals_from_log(case_dir, end_time, save_bool=True, save_path=None):
    """
    Reads a simpleFoam log file and plots residuals for Ux, Uy, Uz, p, k, omega.
    log_file: path to 'log.simpleFoam' generated by your solver
    """
    
    log_file = f"{case_dir}/log.simpleFoam.logfile"
    
    residuals = defaultdict(list)
    
    # Regex to extract variable and final residual
    res_pattern = re.compile(r"Solving for (\w+), Initial residual = [\d.eE+-]+, Final residual = ([\d.eE+-]+)")
    
    # Read log file
    with open(log_file, "r") as f:
        access_p = 0
        for line in f:
            match = res_pattern.search(line)
            if match:
                var, final = match.groups()
                if var == 'p' and access_p % 5 != 0 : access_p += 1
                else :
                    residuals[var].append(float(final))
                    if var == 'p' : access_p += 1
    
    # Plot residuals
    plt.figure(figsize=(8,5))
    colors = {"Ux": "r", "Uy": "g", "Uz": "b", "p": "k", "k": "m", "omega": "c"}
    for var, vals in residuals.items():
        color = colors.get(var, None)
        plt.plot(range(len(vals)), vals, label=var, color=color)
    
    plt.yscale('log')
    plt.xlabel("Iteration")
    plt.ylabel("Residual")
    plt.title("simpleFoam Residuals")
    plt.legend()
    plt.grid(True)
    
    if save_bool and save_path != None :
        plots_dir = os.path.join(case_dir, save_path)
        pathlib.Path(plots_dir).mkdir(parents=True, exist_ok=True)
        plt.savefig(f"{save_path}/residuals_{end_time}.pdf")
    if save_bool and save_path == None : plt.savefig(f"{case_dir}/configurations_saved/{end_time}/plots/residuals_{end_time}.pdf")
    
    plt.show()

def read_scalar(case_dir, patch, end_time):

    filename = f"{case_dir}/postProcessing/{patch}/0/surfaceFieldValue.dat"
    
    iterations = np.zeros(end_time)
    scalars = np.zeros(end_time)
    
    with open(filename, "r") as file :
        for i in range(5) : file.readline()
        index = 0
        for line in file.readlines() :
            if index >= end_time: break
            words = line.split()
            iterations[index] = float(words[0])
            scalars[index] = float(np.float32(words[1]))
            index += 1
    
    return iterations, scalars

def read_vector(case_dir, patch, end_time, len_vector):

    filename = f"{case_dir}/postProcessing/{patch}/0/surfaceFieldValue.dat"
    
    iterations = np.zeros(end_time)
    vectors = np.zeros((end_time, len_vector))
    
    with open(filename, "r") as file :
        for i in range(5) : file.readline()
        index = 0
        for line in file.readlines() :
            if index >= end_time: break
            words = re.split(r'[()]', line)
            iterations[index] = float(words[0])
            for i in range(len_vector) : vectors[index][i] = float(np.float32(words[1].split()[i]))
            index += 1
    
    return iterations, vectors

def plots(case_dir, end_time, save_bool=True, save_path=None):
    
    iterations, mass_flow_inlet = read_scalar(case_dir, "massFlowInlet", end_time)
    _, mass_flow_outlet = read_scalar(case_dir, "massFlowOutlet", end_time)
    mass_flow = mass_flow_inlet + mass_flow_outlet
        
    _, velocity = read_vector(case_dir, "outletVelocity", end_time, 3)
    Ux = velocity[:,0]; Uy = velocity[:,1]; Uz = velocity[:,2]
    
    ### -------- Plots -------- ###
    
    # Residuals
    plot_residuals_from_log(case_dir, end_time, save_bool=save_bool, save_path=save_path)
    
    plt.figure(figsize=(8,5))
    
    # Mass Flow
    plt.plot(iterations, mass_flow, label="Mass Balance")
    plt.xlabel("Iteration")
    plt.ylabel("Mass flow balance [kg/s]")
    plt.title("Mass flow convergence")
    plt.legend()
    plt.grid(True)
    if save_bool and save_path != None :
        plots_dir = os.path.join(case_dir, save_path)
        pathlib.Path(plots_dir).mkdir(parents=True, exist_ok=True)
        plt.savefig(f"{save_path}/mass_flow_iterations_{end_time}.pdf")
    if save_bool and save_path == None : plt.savefig(f"{case_dir}/configurations_saved/{end_time}/plots/mass_flow_iterations_{end_time}.pdf") 
    plt.show()
    
    # Ux
    plt.plot(iterations, Ux, label="Ux")
    plt.xlabel("Iteration")
    plt.ylabel("Ux [m/s]")
    plt.title("Ux convergence at outlet")
    plt.legend()
    plt.grid(True)
    if save_bool and save_path != None :
        plots_dir = os.path.join(case_dir, save_path)
        pathlib.Path(plots_dir).mkdir(parents=True, exist_ok=True)
        plt.savefig(f"{save_path}/Ux_{end_time}.pdf")
    if save_bool and save_path == None : plt.savefig(f"{case_dir}/configurations_saved/{end_time}/plots/Ux_{end_time}.pdf")
    plt.show()
    
    # Uy
    plt.plot(iterations, Uy, label="Uy")
    plt.xlabel("Iteration")
    plt.ylabel("Uy [m/s]")
    plt.title("Uy convergence at outlet")
    plt.legend()
    plt.grid(True)
    if save_bool and save_path != None :
        plots_dir = os.path.join(case_dir, save_path)
        pathlib.Path(plots_dir).mkdir(parents=True, exist_ok=True)
        plt.savefig(f"{save_path}/Uy_{end_time}.pdf")
    if save_bool and save_path == None : plt.savefig(f"{case_dir}/configurations_saved/{end_time}/plots/Uy_{end_time}.pdf")
    plt.show()
    
    # Uz
    plt.plot(iterations, Uz, label="Uz")
    plt.xlabel("Iteration")
    plt.ylabel("Uz [m/s]")
    plt.title("Uz convergence at outlet")
    plt.legend()
    plt.grid(True)
    if save_bool and save_path != None :
        plots_dir = os.path.join(case_dir, save_path)
        pathlib.Path(plots_dir).mkdir(parents=True, exist_ok=True)
        plt.savefig(f"{save_path}/Uz_{end_time}.pdf")
    if save_bool and save_path == None : plt.savefig(f"{case_dir}/configurations_saved/{end_time}/plots/Uz_{end_time}.pdf")
    plt.show()



if __name__ == "__main__" :
    case_dir = "cases/fan_0"
    end_time = 3540
    plots(case_dir, end_time, save_bool=False, save_path=f"{case_dir}/configurations_saved/{end_time}")