import os
import re
import matplotlib.pyplot as plt
import pathlib
from collections import defaultdict

def plot_residuals_from_log(case_dir, end_time):
    """
    Reads a simpleFoam log file and plots residuals for Ux, Uy, Uz, p, k, omega.
    log_file: path to 'log.simpleFoam' generated by your solver
    """
    
    log_file = f"{case_dir}/log.simpleFoam.logfile"
    
    residuals = defaultdict(list)
    
    # Regex to extract variable and final residual
    res_pattern = re.compile(r"Solving for (\w+), Initial residual = [\d.eE+-]+, Final residual = ([\d.eE+-]+)")
    
    # Read log file
    with open(log_file, "r") as f:
        access_p = 0
        for line in f:
            match = res_pattern.search(line)
            if match:
                var, final = match.groups()
                if var == 'p' and access_p % 5 != 0 : access_p += 1
                else :
                    residuals[var].append(float(final))
                    if var == 'p' : access_p += 1
    
    # Plot residuals
    plt.figure(figsize=(8,5))
    colors = {"Ux": "r", "Uy": "g", "Uz": "b", "p": "k", "k": "m", "omega": "c"}
    for var, vals in residuals.items():
        color = colors.get(var, None)
        plt.plot(range(len(vals)), vals, label=var, color=color)
    
    plt.yscale('log')
    plt.xlabel("Iteration")
    plt.ylabel("Residual")
    plt.title("simpleFoam Residuals")
    plt.legend()
    plt.grid(True)
    plt.savefig(f"{case_dir}/plots/{end_time}/residuals_{end_time}.pdf")
    plt.show()
